/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp org.blacksailer.depecher.xml -a DepecherAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DEPECHERADAPTOR_H
#define DEPECHERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.blacksailer.depecher
 */
class DepecherAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.blacksailer.depecher")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.blacksailer.depecher\">\n"
"    <method name=\"openConversation\">\n"
"      <arg direction=\"in\" type=\"x\" name=\"chatId\"/>\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\"/>\n"
"    </method>\n"
"    <method name=\"showApp\">\n"
"      <arg direction=\"in\" type=\"as\" name=\"item\"/>\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\"/>\n"
"    </method>\n"
"    <method name=\"openUrl\">\n"
"      <arg direction=\"in\" type=\"as\" name=\"url\"/>\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DepecherAdaptor(QObject *parent);
    virtual ~DepecherAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    Q_NOREPLY void openConversation(qlonglong chatId);
    Q_NOREPLY void openUrl(const QStringList &url);
    Q_NOREPLY void showApp(const QStringList &item);
Q_SIGNALS: // SIGNALS
};

#endif
